on: [workflow_dispatch]

jobs:
  clear-checksums:                                    #THIS WORKLFOW IS JUST FOR TESTING!!!
    runs-on: ubuntu-latest
    name: Clear Checksums
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/clear-checksums@v4.18.0
        with:
          url: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}