on: [workflow_dispatch]

jobs:
  diff-changelog:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Changelog
      CI_COMMIT_AUTHOR: Continuous Integration              #commit message and author for the push back to the repository
    name: Diff Changelog
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/diff-changelog@v4.18.0     #the used action
        with: 
          changeLogFile: 'example/changelogs/containerchangelog.sql'  #the used changelog
          referenceUrl: ${{ secrets.REFERENCEURL }}                 
          url: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }}                         
          password: ${{ secrets.PASSWORD }}                     #access data of the databases in use -> stored in the GitHub Secrets
          referenceUsername: ${{ secrets.USERNAME }}
          referencePassword: ${{ secrets.PASSWORD }}
       # Commit and push all changed files (in this case the changelog) back to the repository.
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "kammlerl@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push         

#  test-liquibase-action:
 #   needs: diff-changelog
  #  runs-on: ubuntu-latest
   # name: Test Liquibase Action
    #steps:
     # - uses: actions/checkout@v2
      #- uses: liquibase/liquibase-github-action@v2
       # with:
        #  operation: 'update'
         # classpath: 'example/changelogs'
          #changeLogFile: 'mynewchangelog.xml'
          #username: ${{ secrets.USERNAME }}
          #password: ${{ secrets.PASSWORD }}
          #url: ${{ secrets.URL }}