on: [push]

jobs:
  diff-changelog:
    runs-on: ubuntu-latest
    name: Diff Changelog
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/diff-changelog@v4.18.0
        with: 
          diffChangeLog: 'example/changelogs/mychangelog.sql'
          referenceUrl: ${{ secrets.REFERENCEURL }}
          url: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          referenceUsername: ${{ secrets.USERNAME }}
          referencePassword: ${{ secrets.PASSWORD }}
          

  test-liquibase-action:
    needs: diff-changelog
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: ${{ secrets.URL }}