on: [workflow_dispatch]

jobs:
  changelog-sync:
     runs-on: ubuntu-latest
     name: Changelog Sync
     steps:
     - uses: actions/checkout@v3
     - uses: liquibase-github-actions/changelog-sync@v4.18.0    #action in use
       with: 
         changeLogFile: 'example/changelogs/containerchangelog.sql'
         url: ${{ secrets.URL }}
         password: ${{ secrets.PASSWORD }}        #access data of the database in use -> stored in the GitHub Secrets
         username: ${{ secrets.USERNAME }}
     