on: [workflow_dispatch]

jobs:
  update-database:
     runs-on: ubuntu-latest
     name: Update Database
     steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/update-sql@v4.18.0
         with:
          changelogFile: 'example/changelogs/mynewchangelog.xml'
          url: ${{ secrets.URL }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}