on: [workflow_dispatch]

jobs:
 update-database:
    
     runs-on: ubuntu-latest
     name: Update Database
     steps:
       - uses: actions/checkout@v2
       - uses: liquibase/liquibase-github-action@v2
         with:
           operation: 'update'
           classpath: 'example/changelogs'
           changeLogFile: 'mynewchangelog.xml'
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           url: ${{ secrets.URL }}